SysPOGWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('/advertisement', views.advertisement, name='advertisement'),
    path('/buffer', views.buffer, name='buffer'),
    path('/volume', views.volume, name='volume'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from subprocess import *

# Create your views here.
def home(request):
    return render(request, 'home.html')

def advertisement(request):
    if request.method == 'POST':
        option = int(request.POST['advertisement'])
        if option == 1 :
            run(['ethtool', '-s', 'enp0s3', 'speed', '10', 'duplex', 'full', 'autoneg', 'on'], stdout=PIPE)
        elif option == 2:
            run(['ethtool', '-s', 'enp0s3', 'speed', '100', 'duplex', 'full', 'autoneg', 'on'], stdout=PIPE)
        elif option == 3:
            run(['ethtool', '-s', 'enp0s3', 'speed', '1000', 'duplex', 'full', 'autoneg', 'on'], stdout=PIPE)

    return redirect('main:home')

def buffer(request):
    if request.method == 'POST':
        option = int(request.POST['buffer'])
        if option == 1 :
            run(['ethtool', '-G', 'enp0s3', 'rx', '4096', 'tx', '4096'], stdout=PIPE)
        elif option == 2:
            run(['ethtool', '-G', 'enp0s3', 'rx', '2048', 'tx', '2048'], stdout=PIPE)
        elif option == 3:
            run(['ethtool', '-G', 'enp0s3', 'rx', '1024', 'tx', '1024'], stdout=PIPE)
        elif option == 4:
            run(['ethtool', '-G', 'enp0s3', 'rx', '512', 'tx', '512'], stdout=PIPE)
        elif option == 5:
            run(['ethtool', '-G', 'enp0s3', 'rx', '256', 'tx', '256'], stdout=PIPE)

    return redirect('main:home')

def volume(request):
    if request.method == 'POST':
        option = int(request.POST['volume'])
        master = 'Master'
        if option == 1 :
            run(['amixer', 'set', master, '50%'], stdout=PIPE)
        elif option == 2 :
            run(['amixer', 'set', master, '75%'], stdout=PIPE)
        elif option == 3 :
            run(['amixer', 'set', master, '100%'], stdout=PIPE)

    return redirect('main:home')

main/templates/home.html
<head>
    <meta charset = "UTF-8">
    <meta name= "viewport" content="width=device-width, initial-scale=1.0">
    <title>SysPOG</title>
</head>

<body>
    <p>
        Change enp0s3 Advertisement Mode <br>
        1. Change enp0s3 advertisement to 10baseT Full Duplex AutoNeg On<br>
        2. Change enp0s3 advertisement to 100baseT Full Duplex AutoNeg On<br>
        3. Change enp0s3 advertisement to 1000baseT Full Duplex AutoNeg On<br>
    </p>
    <form action="{% url 'main:advertisement' %}" method="POST">
        {% csrf_token %}
        <label for="advertisement">Option for enp0s3 Advertisement Mode (choose 1-3) :</label>
        <input type="number" id="advertisement" name="advertisement" min="1" max="3">
        <button class="btn btn-outline-warning" id="submit_button">Submit</button>
    </form>

    <p>
        Change enp0s3 RX/TX Buffer Size <br>
        1. Change enp0s3 RX/TX Buffer to 4096/4096<br>
        2. Change enp0s3 RX/TX Buffer to 2048/2048<br>
        3. Change enp0s3 RX/TX Buffer to 1024/1024<br>
        4. Change enp0s3 RX/TX Buffer to 512/512<br>
        5. Change enp0s3 RX/TX Buffer to 256/256<br>
    </p>
    <form action="{% url 'main:buffer' %}" method="POST">
        {% csrf_token %}
        <label for="buffer">Option for enp0s3 RX/TX Buffer Size (choose 1-5) :</label>
        <input type="number" id="buffer" name="buffer" min="1" max="5">
        <button class="btn btn-outline-warning" id="submit_button">Submit</button>
    </form>

    <p>
        Choose Audio Volume <br>
        1. 50% <br>
        2. 75% <br>
        3. 100% <br>
    </p>
    <form action="{% url 'main:volume' %}" method="POST">
        {% csrf_token %}
        <label for="volume">Option for Audio Volume (choose 1-3) :</label>
        <input type="number" id="volume" name="volume" min="1" max="3">
        <button class="btn btn-outline-warning" id="submit_button">Submit</button>
    </form>
</body>